services:
  web:
    build: .
    container_name: php-web-app
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.27
    container_name: mysql-db2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gasolinera
      MYSQL_USER: user
      MYSQL_PASSWORD: B4rqu1t0&s0l
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/localhost.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  app:
  db_data:
